Repository softeng-701-group-5/softeng-701-assignment-1, pull requests merged in 2020-03, with the labels that each got.

#10 Initial Commit of Pull Request Template addresses Issue # 3
  .github/pull_request_template.md
Labels: SQUASH

#18 Issue template created closes #1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: SQUASH, documentation, good first issue

#25 Add project description to README closes #8
  README.md
Labels: READY, SQUASH, documentation, good first issue

#24 Issue template for a simple user story closes #23
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: SQUASH, documentation, good first issue

#26 Create basic wiki guidelines closes #6
  .github/wiki_guidelines.md
Labels: READY, SQUASH, documentation, good first issue

#17 Setup react project closes #15
  .gitignore
  client/.gitignore
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.jsx
  client/src/components/Hello.jsx
  client/src/index.js
  client/src/pages/HelloPage.jsx
  client/src/serviceWorker.js
  client/src/styles/styles.css
  client/yarn.lock
Labels: READY, enhancement

#22 Add contribution guidelines closes #4
  CONTRIBUTING.md
Labels: SQUASH, documentation

#31 Create code of conduct
  .github/code_of_conduct.md
Labels: READY, documentation

#32 Update README.md
  client/README.md
Labels: documentation, enhancement

#29 Fetch reddit posts for a users homepage from the reddit api closes #27
  server/.gitignore
  server/pom.xml
  server/src/main/java/com/feeder/server/ApplicationProperties.java
  server/src/main/java/com/feeder/server/controllers/HelloController.java
  server/src/main/java/com/feeder/server/providers/reddit/RedditFeedProvider.java
  server/src/main/resources/application.properties
  server/src/test/java/com/feeder/server/controllers/HelloControllerTests.java
  server/src/test/java/com/feeder/server/providers/reddit/RedditFeedProviderTest.java
  server/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: READY, enhancement

#33 WIP: Added Github workflow for frontend and backend
  .github/workflows/workflow.yml
Labels: READY, enhancement

#39 Configured eslint and prettier for client app formatting/linting
  client/.prettierrc
  client/package.json
  client/yarn.lock
Labels: READY

#36 Install Material UI closes #20
  client/package.json
  client/yarn.lock
Labels: SQUASH, enhancement

#5 docs: Create LICENSE
  LICENSE
Labels: documentation

#45 Setup basic layout of feed page closes #40
  client/src/App.jsx
  client/src/index.js
  client/src/pages/FeedPage.jsx
  client/src/pages/FeedPage.test.jsx
  client/src/pages/HelloPage.jsx
  client/src/styles/styles.css
Labels: enhancement

#48 Feature/generic service provider flow closes #44 and #43
  server/pom.xml
  server/src/main/java/com/feeder/server/ApplicationProperties.java
  server/src/main/java/com/feeder/server/ServerApplication.java
  server/src/main/java/com/feeder/server/controller/MultiFeedController.java
  server/src/main/java/com/feeder/server/controllers/HelloController.java
  server/src/main/java/com/feeder/server/model/DemoData.java
  server/src/main/java/com/feeder/server/model/GenericData.java
  server/src/main/java/com/feeder/server/model/GithubData.java
  server/src/main/java/com/feeder/server/model/RedditData.java
  server/src/main/java/com/feeder/server/model/SpotifyData.java
  server/src/main/java/com/feeder/server/model/TwitterData.java
  server/src/main/java/com/feeder/server/models/Hello.java
  server/src/main/java/com/feeder/server/provider/FeedProvider.java
  server/src/main/java/com/feeder/server/provider/github/GithubFeedProvider.java
  server/src/main/java/com/feeder/server/provider/reddit/RedditClientConfig.java
  server/src/main/java/com/feeder/server/provider/reddit/RedditFeedProvider.java
  server/src/main/java/com/feeder/server/provider/spotify/SpotifyFeedProvider.java
  server/src/main/java/com/feeder/server/provider/twitter/TwitterFeedProvider.java
  server/src/main/java/com/feeder/server/providers/reddit/RedditFeedProvider.java
  server/src/test/java/com/feeder/server/ServerApplicationTests.java
  server/src/test/java/com/feeder/server/controller/MultiFeedControllerIntegrationTest.java
  server/src/test/java/com/feeder/server/controllers/HelloControllerTests.java
  server/src/test/java/com/feeder/server/provider/reddit/RedditClientConfigTest.java
  server/src/test/java/com/feeder/server/provider/reddit/RedditFeedProviderTest.java
  server/src/test/java/com/feeder/server/providers/reddit/RedditFeedProviderTest.java
Labels: enhancement

#56 Create front-end card closes #41
  client/src/assets/github-icon.svg
  client/src/assets/reddit-icon.svg
  client/src/assets/spotify-icon.svg
  client/src/assets/twitter-icon.svg
  client/src/components/Hello.jsx
  client/src/components/Hello.test.jsx
  client/src/components/MediaCard.jsx
  client/src/images/mountain.jpg
  client/src/pages/FeedPage.jsx
Labels: READY, SQUASH, enhancement

#61 Create client snapshot tests closes #58
  client/src/components/MediaCard.test.jsx
  client/src/components/__snapshots__/MediaCard.test.jsx.snap
  client/src/pages/FeedPage.test.jsx
  client/src/pages/HomePage.test.jsx
  client/src/pages/__snapshots__/FeedPage.test.jsx.snap
  client/src/pages/__snapshots__/HomePage.test.jsx.snap
Labels: READY, enhancement

#62 Login Page Prototype
  client/src/assets/bg-4k-min.jpg
  client/src/pages/HomePage.jsx
  client/src/pages/__snapshots__/HomePage.test.jsx.snap
Labels: READY, SQUASH, enhancement

#64 Update formatting of media cards on the feed page
  client/src/components/MediaCard.jsx
  client/src/components/__snapshots__/MediaCard.test.jsx.snap
  client/src/images/mountain.jpg
  client/src/pages/FeedPage.jsx
  client/src/pages/__snapshots__/FeedPage.test.jsx.snap
Labels: READY, SQUASH, enhancement

#71 Implement endpoint /twitter to get twitter feed closes #65
  server/pom.xml
  server/src/main/java/com/feeder/server/ApplicationProperties.java
  server/src/main/java/com/feeder/server/model/TwitterData.java
  server/src/main/java/com/feeder/server/provider/twitter/TwitterCredentials.java
  server/src/main/java/com/feeder/server/provider/twitter/TwitterFeedProvider.java
  server/src/main/resources/application.properties
  server/src/test/java/com/feeder/server/provider/reddit/RedditClientConfigTest.java
Labels: SQUASH, enhancement

#73 Implementation of getting feed from /github endpoint closes #52 and #53
  server/src/main/java/com/feeder/server/ApplicationProperties.java
  server/src/main/java/com/feeder/server/model/GithubData.java
  server/src/main/java/com/feeder/server/model/github/Actor.java
  server/src/main/java/com/feeder/server/model/github/Payload.java
  server/src/main/java/com/feeder/server/model/github/Repository.java
  server/src/main/java/com/feeder/server/provider/github/GithubFeedProvider.java
  server/src/main/resources/application.properties
Labels: SQUASH, enhancement

#74 Implementation of /reddit endpoint closes #28
  server/src/main/java/com/feeder/server/model/RedditData.java
  server/src/main/java/com/feeder/server/provider/reddit/RedditFeedProvider.java
  server/src/test/java/com/feeder/server/provider/reddit/RedditFeedProviderTest.java
Labels: SQUASH, enhancement

#76 Introduce Java code style (auto-format, CI check) closes #13
  .github/workflows/workflow.yml
  CONTRIBUTING.md
  server/pom.xml
  server/src/main/java/com/feeder/server/ApplicationProperties.java
  server/src/main/java/com/feeder/server/controller/MultiFeedController.java
  server/src/main/java/com/feeder/server/model/RedditData.java
  server/src/main/java/com/feeder/server/model/TwitterData.java
  server/src/main/java/com/feeder/server/provider/github/GithubFeedProvider.java
  server/src/main/java/com/feeder/server/provider/reddit/RedditFeedProvider.java
  server/src/main/java/com/feeder/server/provider/twitter/TwitterCredentials.java
  server/src/test/java/com/feeder/server/provider/reddit/RedditFeedProviderTest.java
Labels: enhancement

#77 Modified to only implement Hacker News data model
  server/src/main/java/com/feeder/server/model/GenericData.java
  server/src/main/java/com/feeder/server/model/HackerNewsData.java
Labels: enhancement

#78 Integrate Client and Server, render cards from api data, closes #51, #67
  client/package.json
  client/src/assets/hackernews-icon.svg
  client/src/assets/spotify-icon.svg
  client/src/common/api.js
  client/src/common/mapping.js
  client/src/components/MediaCard.jsx
  client/src/components/__snapshots__/MediaCard.test.jsx.snap
  client/src/pages/FeedPage.jsx
  client/src/pages/__snapshots__/FeedPage.test.jsx.snap
  client/src/styles/styles.css
  client/yarn.lock
  server/src/main/java/com/feeder/server/controller/MultiFeedController.java
Labels: READY, SQUASH, bug, enhancement

#72 Getting started readmes closes #47
  README.md
  client/README.md
  server/README.md
Labels: READY, SQUASH, documentation

#79 Fetch hackernews data closes #55
  server/src/main/java/com/feeder/server/controller/MultiFeedController.java
  server/src/main/java/com/feeder/server/model/SpotifyData.java
  server/src/main/java/com/feeder/server/provider/hackernews/HackerNewsFeedProvider.java
  server/src/main/java/com/feeder/server/provider/spotify/SpotifyFeedProvider.java
  server/src/test/java/com/feeder/server/controller/MultiFeedControllerIntegrationTest.java
Labels: SQUASH, enhancement

#83 Simplify HackerNewsFeedProvider closes #94
  server/src/main/java/com/feeder/server/model/HackerNewsData.java
  server/src/main/java/com/feeder/server/provider/github/GithubFeedProvider.java
  server/src/main/java/com/feeder/server/provider/hackernews/HackerNewsFeedProvider.java
Labels: SQUASH, enhancement

#80 Added label usage to contributor guidelines, closes #63
  CONTRIBUTING.md
Labels: SQUASH, documentation

#85 Show first image on twitter cards if they contain them closes #82
  client/src/common/mapping.js
  server/src/main/java/com/feeder/server/model/TwitterData.java
  server/src/main/java/com/feeder/server/provider/twitter/TwitterFeedProvider.java
Labels: READY, SQUASH, enhancement

#86 Name the web app closes #87
  client/package.json
  client/public/index.html
  client/public/manifest.json
Labels: READY, SQUASH, bug

#97 Feed Page Loader, closes #81
  client/src/pages/FeedPage.jsx
  client/src/pages/__snapshots__/FeedPage.test.jsx.snap
Labels: enhancement

#98 Create Favicon closes #88
  client/public/android-chrome-192x192.png
  client/public/android-chrome-512x512.png
  client/public/apple-touch-icon.png
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/mstile-150x150.png
  client/src/assets/Feedr.png
Labels: READY, enhancement

#105 Add instructions for creating new credentials, closes #104
  server/README.md
Labels: HIGH PRIORITY, READY, SQUASH, documentation

#99 Twitter Feed Provider Unit Testing closes #84
  server/src/main/java/com/feeder/server/provider/twitter/TwitterFeedProvider.java
  server/src/test/java/com/feeder/server/provider/twitter/TwitterFeedProviderTest.java
Labels: enhancement

#96 Media Card Unit Testing, closes #60
  client/src/components/MediaCard.test.jsx
  client/src/components/__snapshots__/MediaCard.test.jsx.snap
Labels: READY, SQUASH, enhancement

#107 HackerNewsFeedProvider testing, closes #95
  server/src/main/java/com/feeder/server/provider/hackernews/HackerNewsFeedProvider.java
  server/src/test/java/com/feeder/server/provider/hackernews/HackerNewsFeedProviderTest.java
Labels: SQUASH

#110 Changed "Spotify" to "Hacker News" in README, closes #109
  README.md
Labels: HIGH PRIORITY, documentation

#112 Backend documentation
  server/src/main/java/com/feeder/server/model/GithubData.java
  server/src/main/java/com/feeder/server/model/HackerNewsData.java
  server/src/main/java/com/feeder/server/model/RedditData.java
  server/src/main/java/com/feeder/server/model/TwitterData.java
  server/src/main/java/com/feeder/server/provider/github/GithubFeedProvider.java
  server/src/main/java/com/feeder/server/provider/hackernews/HackerNewsFeedProvider.java
  server/src/main/java/com/feeder/server/provider/twitter/TwitterFeedProvider.java
Labels: HIGH PRIORITY, SQUASH, backend, documentation
