Repository softeng-701-group-5/softeng-701-assignment-1, pull requests merged in 2020-04, with the labels that each got.

#127 Bugfix/#115 changing home button to logout button
  client/src/components/SearchBox.jsx
  client/src/components/__snapshots__/SearchBox.test.jsx.snap
  client/src/pages/FavouritesPage.jsx
  client/src/pages/FeedPage.jsx
  client/src/pages/__snapshots__/FeedPage.test.jsx.snap
Labels: bug, frontend

#132 Create covid19 data model #123
  server/src/main/java/com/feeder/server/model/CovidNineteenData.java
  server/src/main/java/com/feeder/server/model/GenericData.java
Labels: HIGH PRIORITY, backend

#122 Implement modals for each card #116
  client/src/components/MediaCard.jsx
  client/src/components/__snapshots__/FilterBar.test.jsx.snap
  client/src/components/__snapshots__/MediaCard.test.jsx.snap
  client/src/pages/__snapshots__/FeedPage.test.jsx.snap
Labels: enhancement, frontend

#146 refactor/#128 Refactor Frontend into reusable components
  client/src/components/FeedrModal.jsx
  client/src/components/Header.jsx
  client/src/components/MediaCard.jsx
  client/src/components/__snapshots__/MediaCard.test.jsx.snap
  client/src/pages/FavouritesPage.jsx
  client/src/pages/FeedPage.jsx
  client/src/pages/__snapshots__/FavouritesPage.test.jsx.snap
  client/src/pages/__snapshots__/FeedPage.test.jsx.snap
Labels: REFACTOR, frontend

#148 Add mongodb database and models
  server/pom.xml
  server/src/main/java/com/feeder/server/controller/UserController.java
  server/src/main/java/com/feeder/server/model/User.java
  server/src/main/java/com/feeder/server/repository/UserRepository.java
  server/src/main/java/com/feeder/server/service/UserService.java
  server/src/main/resources/application.properties
Labels: backend

#144 Implemented InfiniteScroll
  client/package.json
  client/src/pages/FavouritesPage.jsx
  client/src/pages/FeedPage.jsx
  client/yarn.lock
Labels: enhancement, frontend

#150 Scrollable modal
  client/src/components/FeedrModal.jsx
Labels: bug, frontend

#153 Feature/136 oauth
  client/.env.example
  client/README.md
  client/package.json
  client/proxy-server/index.js
  client/src/App.jsx
  client/src/components/oauth/CookieManager.js
  client/src/components/oauth/GithubConnect.jsx
  client/src/components/oauth/QueryParser.js
  client/src/components/oauth/RedditConnect.jsx
  client/src/components/oauth/TwitterConnect.jsx
  client/src/components/oauth/index.js
  client/src/configs/feedr-apps.js
  client/src/pages/CallbackPage.jsx
  client/src/pages/ConnectPage.jsx
  client/yarn.lock
Labels: HIGH PRIORITY, enhancement, frontend

#133 Add weather api #131
  README.md
  server/README.md
  server/src/main/java/com/feeder/server/ApplicationProperties.java
  server/src/main/java/com/feeder/server/controller/MultiFeedController.java
  server/src/main/java/com/feeder/server/model/GenericData.java
  server/src/main/java/com/feeder/server/model/WeatherData.java
  server/src/main/java/com/feeder/server/provider/weather/WeatherDataProvider.java
  server/src/main/resources/application.properties
  server/src/test/java/com/feeder/server/controller/MultiFeedControllerIntegrationTest.java
  server/src/test/java/com/feeder/server/provider/weather/WeatherFeedProviderTest.java
Labels: backend, enhancement

#151 Use StackGrid instead of Grid
  client/package.json
  client/src/common/mapping.js
  client/src/pages/FavouritesPage.jsx
  client/src/pages/FeedPage.jsx
  client/yarn.lock
Labels: bug, frontend

#156 Covid19api
  .idea/.gitignore
  .idea/codeStyles/codeStyleConfig.xml
  .idea/sbt.xml
  .idea/vcs.xml
  client/src/components/__snapshots__/FilterBar.test.jsx.snap
  client/src/pages/__snapshots__/FavouritesPage.test.jsx.snap
  client/src/pages/__snapshots__/FeedPage.test.jsx.snap
  server/pom.xml
  server/src/main/java/com/feeder/server/controller/MultiFeedController.java
  server/src/main/java/com/feeder/server/provider/covid19/Covid19FeedProvider.java
  server/src/test/java/com/feeder/server/controller/MultiFeedControllerIntegrationTest.java
  server/src/test/java/com/feeder/server/provider/covidnineteen/CovidNineteenFeedProviderTest.java
  server/src/test/java/com/feeder/server/provider/hackernews/HackerNewsFeedProviderTest.java
Labels: HIGH PRIORITY, WAITING FOR APPROVAL :+1:, backend, dependencies

#160 added covid19 api (#124)
  README.md
  server/pom.xml
  server/src/main/java/com/feeder/server/controller/MultiFeedController.java
  server/src/main/java/com/feeder/server/provider/covid19/Covid19FeedProvider.java
  server/src/test/java/com/feeder/server/controller/MultiFeedControllerIntegrationTest.java
  server/src/test/java/com/feeder/server/provider/covidnineteen/CovidNineteenFeedProviderTest.java
Labels: READY, WAITING FOR APPROVAL :+1:, backend

#161 Feature/dark mode
  client/package.json
  client/src/App.jsx
  client/src/components/FeedrModal.jsx
  client/src/components/Header.jsx
  client/src/components/MediaCard.jsx
  client/src/pages/FavouritesPage.jsx
  client/src/pages/FavouritesPage.test.jsx
  client/src/pages/FeedPage.jsx
  client/yarn.lock
Labels: enhancement, frontend

#165 Issue/164 saving access tokens in the database
  server/pom.xml
  server/src/main/java/com/feeder/server/controller/UserController.java
  server/src/main/java/com/feeder/server/model/user/AccessToken.java
  server/src/main/java/com/feeder/server/model/user/User.java
  server/src/main/java/com/feeder/server/repository/UserRepository.java
  server/src/main/java/com/feeder/server/service/UserService.java
Labels: backend, dependencies

#168 Allow dynamic users to request feeds
  server/src/main/java/com/feeder/server/provider/github/GithubFeedProvider.java
  server/src/main/java/com/feeder/server/provider/reddit/RedditFeedProvider.java
  server/src/main/java/com/feeder/server/provider/twitter/TwitterFeedProvider.java
Labels: backend

#170 Redo github oauth flow to get access token, and move/clean some code
  client/package.json
  client/proxy-server/index.js
  client/src/common/QueryParser.js
  client/src/components/oauth/GithubConnect.jsx
  client/src/components/oauth/RedditConnect.jsx
  client/src/configs/feedr-apps.js
  client/src/pages/CallbackPage.jsx
  client/src/pages/ConnectPage.jsx
  client/yarn.lock
Labels: HIGH PRIORITY, bug, frontend

#173 Integrated COVID19 data
  client/src/common/mapping.js
  client/src/components/FilterBar.jsx
  client/src/components/MediaCard.jsx
  client/src/pages/FeedPage.jsx
Labels: enhancement, frontend

#176 Update Header
  client/src/components/Header.jsx
  client/src/components/SearchBox.jsx
Labels: frontend

#175 Adding link to post from modal card
  client/src/components/FeedrModal.jsx
  client/src/components/MediaCard.jsx
  client/src/components/__snapshots__/MediaCard.test.jsx.snap
  client/src/components/__snapshots__/SearchBox.test.jsx.snap
  client/src/pages/__snapshots__/FavouritesPage.test.jsx.snap
  client/src/pages/__snapshots__/FeedPage.test.jsx.snap
Labels: enhancement, frontend

#182 Add check for covidNineteen and weather api
  client/src/pages/FeedPage.jsx
Labels: HIGH PRIORITY, bug, frontend

#171 Store only the string for access token from the cookie value
  server/src/main/java/com/feeder/server/controller/UserController.java
Labels: backend
